# SQL2API 示例配置文件
# 复制此文件为 config.yaml 并根据需要修改

# 开发环境配置示例
server:
  host: "127.0.0.1"
  port: 8080
  mode: "debug"
  read_timeout: 30
  write_timeout: 30

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database: "sql2api_dev"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  max_lifetime: 60

jwt:
  secret: "development-secret-key-change-in-production-environment-at-least-32-chars"
  expiration: 24
  issuer: "sql2api-dev"

security:
  ip_whitelist:
    - "127.0.0.1"
    - "::1"
    - "192.168.0.0/16"
  enable_cors: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

log:
  level: "debug"
  format: "text"
  output: "stdout"

---
# 生产环境配置示例
# server:
#   host: "0.0.0.0"
#   port: 80
#   mode: "release"
#   read_timeout: 60
#   write_timeout: 60
#
# database:
#   type: "postgres"
#   host: "db.example.com"
#   port: 5432
#   username: "sql2api_user"
#   password: "${DB_PASSWORD}"  # 从环境变量读取
#   database: "sql2api_prod"
#   ssl_mode: "require"
#   max_open_conns: 50
#   max_idle_conns: 20
#   max_lifetime: 120
#
# jwt:
#   secret: "${JWT_SECRET}"      # 从环境变量读取
#   expiration: 8
#   issuer: "sql2api-prod"
#
# security:
#   ip_whitelist:
#     - "10.0.0.0/8"            # 仅允许内网访问
#   enable_cors: false
#
# log:
#   level: "warn"
#   format: "json"
#   output: "file"
#   file: "/var/log/sql2api/app.log"

---
# Oracle 数据库配置示例
# database:
#   type: "oracle"
#   host: "oracle.example.com"
#   port: 1521
#   username: "sql2api_user"
#   password: "oracle_password"
#   service: "ORCL"             # Oracle 服务名
#   max_open_conns: 25
#   max_idle_conns: 10
#   max_lifetime: 60
