# SQL2API 配置文件
# 支持环境变量覆盖，格式：SQL2API_<SECTION>_<KEY>
# 例如：SQL2API_SERVER_PORT=9090

# 服务器配置
server:
  host: "0.0.0.0"           # 监听地址
  port: 8081                # 监听端口
  mode: "debug"             # 运行模式: debug, release, test
  read_timeout: 30          # 读取超时时间（秒）
  write_timeout: 30         # 写入超时时间（秒）
  idle_timeout: 120         # 空闲超时时间（秒）

# 数据库配置
database:
  type: "postgres"          # 数据库类型: postgres, oracle
  host: "localhost"         # 数据库主机
  port: 5432               # 数据库端口
  username: "postgres"      # 用户名
  password: "password"      # 密码
  database: "sql2api"       # 数据库名
  service: ""              # Oracle 服务名（仅 Oracle 需要）
  ssl_mode: "disable"      # PostgreSQL SSL 模式: disable, require, verify-ca, verify-full
  max_open_conns: 25       # 最大打开连接数
  max_idle_conns: 10       # 最大空闲连接数
  max_lifetime: 60         # 连接最大生存时间（分钟）

# JWT 配置
jwt:
  secret: "your-very-long-secret-key-change-in-production-environment-at-least-32-chars"
  expiration: 24           # Token 过期时间（小时）
  issuer: "sql2api"        # 签发者

# 安全配置
security:
  # IP 白名单，支持 CIDR 格式
  ip_whitelist:
    - "127.0.0.1"          # 本地回环
    - "::1"                # IPv6 本地回环
    - "192.168.0.0/16"     # 私有网络
    - "10.0.0.0/8"         # 私有网络
    - "172.16.0.0/12"      # 私有网络
  
  # CORS 配置
  enable_cors: true
  cors_origins:
    - "*"                  # 允许所有来源（生产环境建议限制）

# 日志配置
log:
  level: "info"            # 日志级别: debug, info, warn, error
  format: "json"           # 日志格式: json, text
  output: "stdout"         # 输出方式: stdout, file
  file: "sql2api.log"      # 日志文件路径（当 output 为 file 时）

# 示例：Oracle 数据库配置
# database:
#   type: "oracle"
#   host: "localhost"
#   port: 1521
#   username: "system"
#   password: "oracle"
#   service: "XE"          # Oracle 服务名
#   max_open_conns: 25
#   max_idle_conns: 10
#   max_lifetime: 60

# 示例：生产环境配置
# server:
#   host: "0.0.0.0"
#   port: 80
#   mode: "release"
#   read_timeout: 60
#   write_timeout: 60
#
# jwt:
#   secret: "production-secret-key-must-be-very-long-and-secure"
#   expiration: 8
#
# security:
#   ip_whitelist:
#     - "10.0.0.0/8"       # 仅允许内网访问
#   enable_cors: false
#
# log:
#   level: "warn"
#   format: "json"
#   output: "file"
#   file: "/var/log/sql2api/app.log"
